#Task 2

#Importing necessary libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Data Preparation

#Upload and Read train.csv

In [ ]:
from google.colab import files
# 📋 Upload train data
uploaded = files.upload()
# Load train data
train_data = pd.read_csv('Train.csv')
print(train_data.head())

Saving Train.csv to Train.csv
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

#Upload and Read test.csv

In [ ]:
# 📋 Upload test.csv
uploaded = files.upload()
# Load test data
test_data = pd.read_csv('Test.csv')
print(test_data.head())

Saving Test.csv to Test.csv
   PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female
2          894       2                     Myles, Mr. Thomas Francis    male
3          895       3                              Wirz, Mr. Albert    male
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked
0  34.5      0      0   330911   7.8292   NaN        Q
1  47.0      1      0   363272   7.0000   NaN        S
2  62.0      0      0   240276   9.6875   NaN        Q
3  27.0      0      0   315154   8.6625   NaN        S
4  22.0      1      1  3101298  12.2875   NaN        S

#Upload and Read gender_submission.csv

In [ ]:
# 📋 Upload gender_submission.csv
uploaded = files.upload()
# Load gender submission data
gender_data = pd.read_csv('Gender-submission.csv')
print(gender_data.head())

Saving Gender-submission.csv to Gender-submission.csv
   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

#Initial Data Exploration
Basic checks to understand the structure, columns, and quality of the Titanic dataset.

In [ ]:
# Concatenate train and test data for analysis

data = pd.concat([train_data, test_data], sort=False)
print("Combined Data Sample:")
print(data.head())

Combined Data Sample:
   PassengerId  Survived  Pclass  \
0            1       0.0       3
1            2       1.0       1
2            3       1.0       3
3            4       1.0       1
4            5       0.0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

#Display First 5 rows

In [ ]:
data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

#Display Last 5 rows

In [ ]:
data.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,NaN,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,NaN,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,NaN,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,NaN,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

#Checking Columns and shape

In [ ]:
# Check Columns and Shape

print("Column Names:")
print(data.columns)

print("\nShape of the Data (rows, columns):")
print(data.shape)

Column Names:
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

Shape of the Data (rows, columns):
(1309, 12)

#Check data types

In [ ]:
# Data Types

print(data.info())

<class 'pandas.core.frame.DataFrame'>
Index: 1309 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object
 11  Embarked     1307 non-null   object
dtypes: float64(3), int64(4), object(5)
memory usage: 132.9+ KB
None

#Checking the null values

In [ ]:
# Check for Duplicates and Null Values

duplicate_count = data.duplicated().sum()
print(f"Number of Duplicate Rows: {duplicate_count}")

print("\nMissing Values in Each Column:")
data.isnull().sum()

Number of Duplicate Rows: 0

Missing Values in Each Column:

PassengerId       0
Survived        418
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

In [ ]:
# Detailed Data Info

print("Detailed Info on DataFrame:")
data.info()

Detailed Info on DataFrame:
<class 'pandas.core.frame.DataFrame'>
Index: 1309 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object
 11  Embarked     1307 non-null   object
dtypes: float64(3), int64(4), object(5)
memory usage: 132.9+ KB

#Data Cleaning and Feature Engineering
Fill missing values and create new features like Family Size and Age Group.

In [ ]:
#Check for and fill missing values

print("Missing Value Counts Before Cleaning:")
print(data.isnull().sum())

# Fill missing values
data['Survived'] = data['Survived'].fillna(data['Survived'].mode()[0])
data['Age'] = data['Age'].fillna(data['Age'].mean())
data['Fare'] = data['Fare'].fillna(data['Fare'].mean())
data['Cabin'] = data['Cabin'].fillna(data['Cabin'].mode()[0])
data['Embarked'] = data['Embarked'].fillna(data['Embarked'].mode()[0])

print("Missing Value Counts After Cleaning:")
print(data.isnull().sum())

Missing Value Counts Before Cleaning:
PassengerId       0
Survived        418
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64
Missing Value Counts After Cleaning:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [ ]:
# Feature Engineering

# Family Size
data['Family_size'] = data['SibSp'] + data['Parch'] + 1

# AgeGroup Binning
bins = [0, 12, 19, 35, 60, 100]
labels = ['Child', 'Teen', 'Young Adult', 'Adult', 'Senior']
data['AgeGroup'] = pd.cut(data['Age'], bins=bins, labels=labels)

print(data[['Family_size', 'Age', 'AgeGroup']].head())

   Family_size   Age     AgeGroup
0            2  22.0  Young Adult
1            2  38.0        Adult
2            1  26.0  Young Adult
3            2  35.0  Young Adult
4            1  35.0  Young Adult

#Categorical & Numerical Columns

In [ ]:
# Categorical & Numeric Columns
cat_values = data.select_dtypes(include=['object'])
num_values = data.select_dtypes(include=['int64','float64'])
print('Categorical columns:', cat_values.columns.tolist())
print('Numerical columns:', num_values.columns.tolist())

Categorical columns: ['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']
Numerical columns: ['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Family_size']

#Distribution of Sex

In [ ]:
# Distribution of Sex
import plotly.express as px

sex_counts = data['Sex'].value_counts().reset_index()
sex_counts.columns = ['Sex', 'Count']
fig = px.bar(
    sex_counts,
    x='Sex', y='Count', color='Sex',
    color_discrete_map={'male':'royalblue','female':'hotpink'},
    title='Distribution of Sex',
    labels={'Count':'Passenger Count'}
)
fig.update_layout(width=600, height=500) # Set figure size for Plotly
fig.show()

In [ ]:
# Print value counts
print(data['Sex'].value_counts())

Sex
male      843
female    466
Name: count, dtype: int64

In [ ]:
Tickets_count = data['Ticket'].value_counts()
print(Tickets_count)

data['Ticket'].mode()

Ticket
CA. 2343        11
1601             8
CA 2144          8
347082           7
S.O.C. 14879     7
                ..
A.5. 3236        1
347086           1
365237           1
334915           1
28666            1
Name: count, Length: 929, dtype: int64

0    CA. 2343
Name: Ticket, dtype: object

In [ ]:
data['Ticket'].nunique()

929

#Survival Count by Family Type

In [ ]:
#Survival Count by Family Type
def family_type(row):
    if row['Family_size'] == 1:
        return 'Single'
    elif row['Family_size'] <= 4:
        return 'Small Family'
    else:
        return 'Large Family'

data['Family_type'] = data.apply(family_type, axis=1)

family_type_survival = data.groupby(['Family_type','Survived']).size().reset_index(name='Count')
fig = px.bar(
    family_type_survival,
    x='Family_type', y='Count', color='Survived', barmode='group',
    color_discrete_sequence=["indianred","mediumseagreen"],
    title='Survival Count by Family Type',
    labels={'Family_type':'Family Type','Count':'Passenger Count','Survived':'Survived (0 = No, 1 = Yes)'}
)
fig.update_layout(width=800, height=600) # Set figure size for Plotly
fig.show()

#Sex Distribution for Most Sold Ticket

In [ ]:
#Sex Distribution for Most Sold Ticket
most_common_ticket = data['Ticket'].value_counts().idxmax() # Calculate most common ticket
print("Most sold ticket:", most_common_ticket) # Print most common ticket
print() # Print a newline for better formatting

filtered_passangers = data[data['Ticket'] == most_common_ticket]
sex_counts_most_ticket = filtered_passangers['Sex'].value_counts().reset_index()
sex_counts_most_ticket.columns=['Sex','Count']

fig = px.bar(
    sex_counts_most_ticket,
    x='Sex', y='Count', color='Sex',
    color_discrete_map={'male':'teal','female':'salmon'}, # Changed colors
    title=f'Sex Distribution for Most Sold Ticket: {most_common_ticket}',
    labels={'Count':'Passenger Count'}
)
fig.update_layout(width=800, height=600) # Set figure size for Plotly
fig.show()

Most sold ticket: CA. 2343

#Sex Distribution for least Sold Ticket

In [ ]:
#Sex Distribution for least Sold Ticket
least_sold_ticket = data['Ticket'].value_counts().idxmin()
print("Least sold ticket:", least_sold_ticket)
print()

filtered_passengers = data[data['Ticket'] == least_sold_ticket]
print(f"Number of passengers with the least sold ticket ({least_sold_ticket}): {len(filtered_passengers)}") # Add count of passengers

sex_counts = filtered_passengers['Sex'].value_counts().reset_index()
sex_counts.columns = ['Sex', 'Count']

# Ensure both male and female are in the sex_counts for plotting and printing
all_sexes = pd.DataFrame({'Sex': ['male', 'female'], 'Count': 0})
sex_counts = pd.merge(all_sexes, sex_counts, on='Sex', how='left', suffixes=('_all', '_filtered')).fillna(0)
sex_counts['Count'] = sex_counts['Count_all'] + sex_counts['Count_filtered']
sex_counts = sex_counts[['Sex', 'Count']]


print(sex_counts)

import plotly.express as px

fig = px.bar(sex_counts,
             x='Sex',
             y='Count',
             color='Sex',
             title=f'Sex Distribution for Least Sold Ticket: {least_sold_ticket}') # Updated title
fig.update_layout(width=600, height=500) # Set figure size for Plotly
fig.show()

Least sold ticket: SC/PARIS 2159

Number of passengers with the least sold ticket (SC/PARIS 2159): 1
      Sex  Count
0    male    1.0
1  female    0.0

In [ ]:
# lets check how many survived in both the above cases

most_common_ticket_survived = data[(data['Ticket']) == most_common_ticket]['Survived'].value_counts()
print(most_common_ticket_survived)

least_sold_ticket_survived = data[(data['Ticket']) == least_sold_ticket]['Survived'].value_counts()
print(least_sold_ticket_survived)

Survived
0.0    11
Name: count, dtype: int64
Survived
0.0    1
Name: count, dtype: int64

In [ ]:
Survived_sex_data = data.groupby(['Sex','Survived']).size().reset_index()
print(Survived_sex_data)

Total_sex_count = data['Sex'].value_counts()
print("Total sex count is : ",Total_sex_count)
print()
survived_male_count = data[(data['Sex'] == 'male') & (data['Survived'] == 1)]['Sex'].count()
print("The male count who survived : ",survived_male_count)
print()

Survived_male_percent = (survived_male_count / Total_sex_count['male']) * 100
print("The survived male percent : ",Survived_male_percent)
print()
Survived_female_count = data[(data['Sex']=='female') & (data['Survived']==1)]['Sex'].count()
print("The Survived Female Count : ",Survived_female_count)
print()
Survived_female_percent = (Survived_female_count / Total_sex_count['female']) * 100
print("the Survived Female Percentage : ",Survived_female_percent)
print()
#survived_male_percent = data['Survived'][0].value_counts(normalize=True)*100

#print(survived_male_percent)

      Sex  Survived    0
0  female       0.0  233
1  female       1.0  233
2    male       0.0  734
3    male       1.0  109
Total sex count is :  Sex
male      843
female    466
Name: count, dtype: int64

The male count who survived :  109

The survived male percent :  12.930011862396205

The Survived Female Count :  233

the Survived Female Percentage :  50.0

In [ ]:
Embarked_count = data['Embarked'].value_counts()

print(f"The embarked count will be : ",Embarked_count)
print()

The embarked count will be :  Embarked
S    916
C    270
Q    123
Name: count, dtype: int64

In [ ]:
Embarked_sex_Survives_data = data.groupby(['Embarked','Sex','Survived']).size().reset_index()

print("The Embarked_sex_Survives_data will be : ",Embarked_sex_Survives_data)

The Embarked_sex_Survives_data will be :     Embarked     Sex  Survived    0
0         C  female       0.0   49
1         C  female       1.0   64
2         C    male       0.0  128
3         C    male       1.0   29
4         Q  female       0.0   33
5         Q  female       1.0   27
6         Q    male       0.0   60
7         Q    male       1.0    3
8         S  female       0.0  151
9         S  female       1.0  142
10        S    male       0.0  546
11        S    male       1.0   77

In [ ]:
#total number of survived

Embarked_sex_Survives_data_count  = Embarked_sex_Survives_data[Embarked_sex_Survives_data['Survived'] == 1]
print("The Embarked_sex_Survives_data_count will be :",Embarked_sex_Survives_data_count)

The Embarked_sex_Survives_data_count will be :    Embarked     Sex  Survived    0
1         C  female       1.0   64
3         C    male       1.0   29
5         Q  female       1.0   27
7         Q    male       1.0    3
9         S  female       1.0  142
11        S    male       1.0   77

In [ ]:
#total number of survived

Embarked_sex_Survives_data_Male_count = Embarked_sex_Survives_data[(Embarked_sex_Survives_data['Survived'] == 1) & (Embarked_sex_Survives_data['Sex'] == 'male')]
print("The Embarked_sex_Survives_data_Male_count will be :",Embarked_sex_Survives_data_Male_count)
print()

Embarked_sex_Survives_data_Female_count = Embarked_sex_Survives_data [(Embarked_sex_Survives_data['Survived'] ==1 ) & (Embarked_sex_Survives_data['Sex']=='female')]
print("The Embarked_sex_Survives_data_Female_count will be :",Embarked_sex_Survives_data_Female_count)
print()

Embarked_sex_death_data_Male_count = Embarked_sex_Survives_data[(Embarked_sex_Survives_data['Survived']==0)&(Embarked_sex_Survives_data['Sex']=='male')]
print("The Embarked_sex_death_data_Male_count will be :",Embarked_sex_death_data_Male_count)
print()

Embarked_sex_death_data_Female_count = Embarked_sex_Survives_data[(Embarked_sex_Survives_data['Survived']==0)&(Embarked_sex_Survives_data['Sex']=='female')]
print("The Embarked_sex_death_data_Female_count will be :",Embarked_sex_death_data_Female_count)
print()

The Embarked_sex_Survives_data_Male_count will be :    Embarked   Sex  Survived   0
3         C  male       1.0  29
7         Q  male       1.0   3
11        S  male       1.0  77

The Embarked_sex_Survives_data_Female_count will be :   Embarked     Sex  Survived    0
1        C  female       1.0   64
5        Q  female       1.0   27
9        S  female       1.0  142

The Embarked_sex_death_data_Male_count will be :    Embarked   Sex  Survived    0
2         C  male       0.0  128
6         Q  male       0.0   60
10        S  male       0.0  546

The Embarked_sex_death_data_Female_count will be :   Embarked     Sex  Survived    0
0        C  female       0.0   49
4        Q  female       0.0   33
8        S  female       0.0  151

#Survival and Embarked Location by Sex

In [ ]:
#Survival and Embarked Location by Sex
embarked_sex_survives_data = data.groupby(['Embarked','Sex','Survived']).size().reset_index(name='Count')
fig = px.bar(
    embarked_sex_survives_data,
    x='Embarked', y='Count', color='Survived', barmode='group', facet_col='Sex',
    color_discrete_sequence=["indianred","mediumseagreen"],
    title='Survival by Embarked Location and Sex',
    labels={'Embarked':'Embarked Port','Count':'Passenger Count','Survived':'Survived (0 = No, 1 = Yes)'}
)
fig.update_layout(width=800, height=600) # Set figure size for Plotly
fig.show()

In [ ]:
Pclass_Survived_data = data.groupby(['Pclass','Survived','Sex']).size().reset_index()
print("the Pclass_Survived_data is :",Pclass_Survived_data)

Pclass_value_counts = data['Pclass'].value_counts()
print("the Pclass_value_counts is :",Pclass_value_counts.head())

the Pclass_Survived_data is :     Pclass  Survived     Sex    0
0        1       0.0  female   53
1        1       0.0    male  134
2        1       1.0  female   91
3        1       1.0    male   45
4        2       0.0  female   36
5        2       0.0    male  154
6        2       1.0  female   70
7        2       1.0    male   17
8        3       0.0  female  144
9        3       0.0    male  446
10       3       1.0  female   72
11       3       1.0    male   47
the Pclass_value_counts is : Pclass
3    709
1    323
2    277
Name: count, dtype: int64

In [ ]:
# number of passangers survived in all the three types of Pclass

pclass_1_male_survivors = data[(data['Pclass'] == 1) &
                               (data['Survived'] == 1) &
                               (data['Sex'] == 'male')]

# Print count
print(f"Number of Male Survivors survived in Pclass 1: {len(pclass_1_male_survivors)}\n")


pclass_1_female_survivors = data[(data['Pclass']==1)&
                                 (data['Survived']==1)&
                                 (data['Sex']=='female')]

print(f"Number of Female Survivors survived in Pclass 1: {len(pclass_1_female_survivors)}\n")

pclass_2_male_survivors_survived = data[(data['Pclass']==2)&
                                 (data['Survived']==1)&
                                 (data['Sex']=='male')]

print(f"Number of Male Survivors survived in Pclass 2: {len(pclass_2_male_survivors_survived)}\n")

pclass_2_female_survivors_survived = data[(data['Pclass']==2)&
                                 (data['Survived']==1)&
                                 (data['Sex']=='female')]

print(f"Number of Female Survivors survived in Pclass 2: {len(pclass_2_female_survivors_survived)}\n")

pclass_3_male_survivors_survived = data[(data['Pclass']==3)&
                                 (data['Survived']==1)&
                                 (data['Sex']=='male')]


print(f"Number of Male Survivors survived in Pclass 3: {len(pclass_3_male_survivors_survived)}\n")

pclass_3_female_survivors_survived = data[(data['Pclass']==3)&
                                 (data['Survived']==1)&
                                 (data['Sex']=='female')]

print(f"Number of Female Survivors survived in Pclass 3: {len(pclass_3_female_survivors_survived)}\n")

Number of Male Survivors survived in Pclass 1: 45

Number of Female Survivors survived in Pclass 1: 91

Number of Male Survivors survived in Pclass 2: 17

Number of Female Survivors survived in Pclass 2: 70

Number of Male Survivors survived in Pclass 3: 47

Number of Female Survivors survived in Pclass 3: 72

In [ ]:
# number of passangers did not survived in all the three types of Pclass

pclass_1_male_survivors_not_survived = data[(data['Pclass'] == 1) &
                                       (data['Survived'] ==0)&
                                            (data['Sex'] == 'male')]


print(f"Number of Male Survivors not survived in Pclass 1: {len(pclass_1_male_survivors_not_survived)}\n")

pclass_1_female_survivors_not_survived = data[(data['Pclass']==1)&
                                 (data['Survived']==0)&
                                 (data['Sex']=='female')]
print(f"Number of Female Survivors not survived in Pclass 1: {len(pclass_1_female_survivors_not_survived)}\n")

pclass_2_male_survivors_not_survived = data[(data['Pclass']==2)&
                                 (data['Survived']==0)&
                                 (data['Sex']=='male')]


print(f"Number of Female Survivors not survived in Pclass 2: {len(pclass_2_male_survivors_not_survived)}\n")

pclass_2_female_survivers_not_survived = data[(data['Pclass']==2)&
                                              (data['Survived']==0)&
                                              (data['Sex']=='female')]
print(f"Number of Female Survivors not survived in Pclass 2: {len(pclass_2_female_survivers_not_survived)}\n")

pclass_3_male_survivors_not_survived = data[(data['Pclass']==3)&
                                            (data['Survived']==0)&
                                            (data['Sex']=='male')]

print(f"Number of male Survivors not survived in Pclass 3: {len(pclass_3_male_survivors_not_survived)}\n")

pclass_3_female_survivors_not_survived = data[(data['Pclass']==3)&
                                              (data['Survived']==0)&
                                              (data['Sex']=='female')]

print(f"Number of Female Survivors not survived in Pclass 3: {len(pclass_3_female_survivors_not_survived)}\n")

Number of Male Survivors not survived in Pclass 1: 134

Number of Female Survivors not survived in Pclass 1: 53

Number of Female Survivors not survived in Pclass 2: 154

Number of Female Survivors not survived in Pclass 2: 36

Number of male Survivors not survived in Pclass 3: 446

Number of Female Survivors not survived in Pclass 3: 144

#Age Distribution by Survival

In [ ]:
# Age Distribution by Survival
fig = px.box(
    data,
    x='Survived', y='Age', color='Survived',
    color_discrete_sequence=["indianred", "mediumseagreen"],
    title='Age Distribution by Survival',
    labels={'Survived':'Survived (0 = No, 1 = Yes)','Age':'Passenger Age'}
)
fig.update_layout(width=800, height=600) # Set figure size for Plotly
fig.show()

#Age Distribution by Passenger Class

In [ ]:
#Age Distribution by Passenger Class
fig = px.histogram(
    data,
    x='Age', color='Pclass', nbins=30, barmode='overlay',
    color_discrete_map={1:"goldenrod",2:"blue",3:"mediumorchid"},
    title='Age Distribution by Passenger Class',
    labels={'Age':'Passenger Age','Pclass':'Passenger Class'}
)
fig.update_traces(opacity=0.6)
fig.update_layout(width=800, height=600) # Set figure size for Plotly
fig.show()

#Survival Count by Age Group

In [ ]:
#Survival Count by Age Group
agegroup_survival = data.groupby(['AgeGroup', 'Survived']).size().reset_index(name='Count')
fig = px.bar(
    agegroup_survival,
    x='AgeGroup', y='Count', color='Survived', barmode='group',
    color_discrete_sequence=["indianred", "mediumseagreen"],
    title='Survival Count by Age Group',
    labels={'Survived':'Survived (0 = No, 1 = Yes)', 'Count':'Passenger Count'}
)
fig.update_layout(width=800, height=600) # Set figure size for Plotly
fig.show()

/tmp/ipython-input-17596578.py:2: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [ ]:
data['Parch'].describe()

count    1309.000000
mean        0.385027
std         0.865560
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         9.000000
Name: Parch, dtype: float64

In [ ]:
Sibsp_parch_Sex_df = data[['SibSp','Parch','Sex']]

print(Sibsp_parch_Sex_df.head())

   SibSp  Parch     Sex
0      1      0    male
1      1      0  female
2      0      0  female
3      1      0  female
4      0      0    male

In [ ]:
SibSp_value_counts = Sibsp_parch_Sex_df['SibSp'].value_counts()
print(SibSp_value_counts)

SibSp
0    891
1    319
2     42
4     22
3     20
8      9
5      6
Name: count, dtype: int64

In [ ]:
Parch_value_counts = Sibsp_parch_Sex_df['Parch'].value_counts()

print(Parch_value_counts)

Parch
0    1002
1     170
2     113
3       8
5       6
4       6
6       2
9       2
Name: count, dtype: int64

In [ ]:
data['Family_size'] = data['SibSp'] + data['Parch'] + 1 # Correct calculation for family size

#Survived by Family Size Count

In [ ]:
#Survived by Family Size Count
family_survival_counts = data.groupby(['Family_size','Survived']).size().reset_index(name='Count')
fig = px.bar(
    family_survival_counts,
    x='Family_size', y='Count', color='Survived', barmode='group',
    color_discrete_sequence=["indianred", "mediumseagreen"],
    title='Survived vs Family Size Count',
    labels={'Family_size':'Family Size','Count':'Passenger Count','Survived':'Survived (0 = No, 1 = Yes)'}
)
fig.update_layout(width=800, height=600) # Set figure size for Plotly
fig.show()

#Survival Count by Sibling/Spouse Count

In [ ]:
#Survival Count by Sibling/Spouse Count
sibsp_survival_counts = data.groupby(['SibSp','Survived']).size().reset_index(name='Count')
fig = px.bar(
    sibsp_survival_counts,
    x='SibSp', y='Count', color='Survived', barmode='group',
    color_discrete_sequence=["indianred", "mediumseagreen"],
    title='Survival Count by Siblings/Spouses',
    labels={'SibSp':'Number of Siblings/Spouses','Count':'Passenger Count','Survived':'Survived (0 = No, 1 = Yes)'}
)
fig.update_layout(width=800, height=600) # Set figure size for Plotly
fig.show()